import { type DebtLoanStatus } from '@/core/domain/entities/debt-loan';
import { type Currency } from '@/core/domain/enums/currency.enum';

/**
 * Allowed billing cadences for a MonthlyService. The backend stores these as
 * raw integers with a DB CHECK constraint — keep them in sync if the column
 * ever expands.
 */
export const MONTHLY_SERVICE_FREQUENCIES = [1, 3, 6, 12] as const;
export type MonthlyServiceFrequencyValue = (typeof MONTHLY_SERVICE_FREQUENCIES)[number];

/**
 * One row from `linkedDebts[]` on `MonthlyServiceResponseDto` — a `LOAN`
 * (module Deudas/Préstamos) generated by a shared-service payment split
 * (`sourceMonthlyServicePaymentId`). Always `PENDING` in this array —
 * `SETTLED` linked debts drop out and remain visible only in `GET /debts`.
 * `id` is the underlying `DebtLoan` id — use it for `POST /debts/:id/settle`.
 */
export interface LinkedDebt {
  id: string;
  reference: string;
  remainingAmount: number;
  status: DebtLoanStatus;
}

/**
 * i18n keys (without the `monthlyServices.frequency.` prefix) that the UI uses
 * to label each cadence in selects, badges, and group headers.
 */
export const MONTHLY_SERVICE_FREQUENCY_LABEL_KEYS: Record<MonthlyServiceFrequencyValue, string> = {
  1: 'monthly',
  3: 'quarterly',
  6: 'semiannual',
  12: 'annual',
};

export interface MonthlyService {
  id: string;
  userId: string;
  name: string;
  categoryId: string;
  currency: Currency;
  /**
   * Billing cadence in months. Backend restricts to {1, 3, 6, 12} via CHECK
   * constraint. Default is 1 (mensual). Immutable after creation — the form
   * only shows the select when creating, disabled while editing.
   */
  frequencyMonths: MonthlyServiceFrequencyValue;
  estimatedAmount: number | null;
  dueDay: number | null;
  /** 'YYYY-MM' — first period this service is billed for. */
  startPeriod: string;
  /** 'YYYY-MM' of the last period the user marked as paid/skipped. Null before any pay/skip. */
  lastPaidPeriod: string | null;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
  // Backend-computed derivatives (always present in list/detail responses):
  /** 'YYYY-MM' of the next period that needs action. Computed in the user timezone. */
  nextDuePeriod: string;
  /** True when `nextDuePeriod` is earlier than the user's current month. */
  isOverdue: boolean;
  /** True when `lastPaidPeriod === currentMonth` in the user timezone. */
  isPaidForCurrentMonth: boolean;
  /**
   * Sum of EXPENSE transactions linked to this service for the current
   * calendar month, in the user's timezone. Drives the per-currency
   * "Pagado / Estimado" KPI on the services dashboard.
   *
   * **Only authoritative on `GET /monthly-services` (the list endpoint).**
   * Single-service endpoints (`GET /:id`, `POST`, `PATCH`, `POST /:id/pay`,
   * etc.) emit `0` — the backend doesn't recompute the aggregate for those
   * responses because the KPI lives on the list view. After a pay/skip the
   * frontend must invalidate the list query to see the fresh sum.
   *
   * Always a number (never null) — services with no payments this month are
   * `0`, not undefined. Lets the KPI reducer sum without nullish guards.
   */
  paidAmountForCurrentMonth: number;
  /**
   * `LOAN`s generated by shared-service payment splits for this service,
   * still `PENDING`. Always present — `[]` when the service has none.
   *
   * **Only authoritative on `GET /monthly-services` (list) and
   * `GET /monthly-services/:id` (detail)** — same precedent as
   * `paidAmountForCurrentMonth`. Other endpoints (`POST`, `PATCH`,
   * `/skip`, `/archive`) emit `[]` by default.
   */
  linkedDebts: LinkedDebt[];
}
